booksite/booksite/background/urls.py
# -*- encoding:utf-8 -*-
from django.conf.urls import url
from .views import (
    index,
    replace,
    delete_rule, edit_rule, apply_rule,
    replace_page, replace_book,
    tuijian, fengtui_create, jingtui_create,
    del_tuijian,
    book_search, book_jx, book_ft, book_jt,
    book_jiuzhenggengxin,
    book_page_next_zipper,
    get_new_book,
)

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^replace/$', replace, name="replace"),
    url(r'^replace/delete/(?P<pk>\d+)/$', delete_rule, name="delete_rule"),
    url(r'^replace/edit/(?P<pk>\d+)/$', edit_rule, name="edit_rule"),
    url(r'^replace/apply/(?P<pk>\d+)/$', apply_rule, name="apply_rule"),
    url(r'^replace/page/$', replace_page, name="replace_page"),
    url(r'^replace/book/$', replace_book, name="replace_book"),
    url(r'^tuijian/$', tuijian, name="tuijian"),
    url(r'^tuijian/create/fengtui/$', fengtui_create, name="fengtui_create"),
    url(r'^tuijian/create/jingtui/$', jingtui_create, name="jingtui_create"),
    url(r'^tuijian/delete/(?P<model>ft|jt)/(?P<book_id>\d+)/$', del_tuijian, name="del_tuijian"),
    url(r'^booksearch/$', book_search, name="book_search"),
    url(r'^booksearch/jx/$', book_jx, name="book_jx"),
    url(r'^booksearch/ft/$', book_ft, name="book_ft"),
    url(r'^booksearch/jt/$', book_jt, name="book_jt"),
    url(r'^booksearch/jxall/$', book_jiuzhenggengxin, name="book_jiuzhenggengxin"),
    url(r'^booksearch/pagezipper/$', book_page_next_zipper, name="book_page_next_zipper"),
    url(r'^newbook/$', get_new_book, name="newbook"),
]

booksite/booksite/urls.py
# -*- coding: utf-8 -*-
import django.contrib.auth.views
from django.contrib.sitemaps import views as sitemap_views
# from django.views.generic.base import TemplateView
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from graphene_django.views import GraphQLView
from booksite.usercenter.views import (
    login_view, signup, logout_view
)
from booksite.sitemap import BookSitemaps
admin.autodiscover()

sitemaps = {
    'books': BookSitemaps()
}

html5_urls = [
    url(r'', include('booksite.h5.urls')),
    url(r'account/', include('booksite.usercenter.mburls')),
]

password_reset_urls = [
    url(r'^$', django.contrib.auth.views.password_reset,
       {'template_name': 'usercenter/password_reset_form.html',
        'email_template_name': 'usercenter/password_reset_email.html',}, name='password_reset'),
    url(r'^done/$', django.contrib.auth.views.password_reset_done,
        {'template_name': 'usercenter/password_reset_done.html'}, name='password_reset_done'),
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', django.contrib.auth.views.password_reset_confirm,
        {'template_name': 'usercenter/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^complete/$', django.contrib.auth.views.password_reset_complete,
        {'template_name': 'usercenter/password_reset_complete.html'}, name='password_reset_complete'),
]

urlpatterns = [
    url(r'', include('booksite.book.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^comments/', include('django_comments.urls')),

    url(r'^sitemap.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^robots.txt', include('robots.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^usercenter/', include('booksite.usercenter.urls')),
    url(r'^login/$', login_view, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^resetpassword/', include(password_reset_urls)),

    url(r'^mobile/', include((html5_urls,'h5',), namespace=None)),

    url(r'^bbg/', include('booksite.background.urls', namespace='bbg', app_name='booksite.background')),
]


if settings.DEBUG:
    import booksite.book.views
    urlpatterns += [url(r'^media/book/(?P<path>.*)$', booksite.book.views.bookpage_zip, name='zippage')]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksite/booksite/background/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from booksite.book.models import BookPage, Book
from .models import ReplaceRule, FengTui, JingTui


class TuiJianForm(forms.Form):
    book_id = forms.CharField(label="书名", max_length=50, required=True)

    def __init__(self, model=FengTui, *args, **kwargs):
        super(TuiJianForm, self).__init__(*args, **kwargs)
        if model not in (FengTui, JingTui):
            raise TypeError("model not in (FengTui, JingTui)!")
        self.tuijian_model = model

    def clean_book_id(self):
        try:
            book = Book.objects.get(title=self.cleaned_data['book_id'])
        except Book.DoesNotExist:
            raise forms.ValidationError("Book does not exist!")
        self.book = book
        return self.cleaned_data['book_id']

    def save(self):
        if self.is_valid():
            tuijian = self.tuijian_model()
            tuijian.add(self.book)
            tuijian.save()
        else:
            raise forms.ValidationError()


class ReplaceRuleCreateForm(forms.Form):
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)

    def save(self):
        if self.is_valid():
            new_rule = ReplaceRule(
                self.cleaned_data['rule_res'].encode('utf-8'),
                self.cleaned_data['replace_to'].encode('utf-8'),
            )
            new_rule.save()
        else:
            raise forms.ValidationError()


class ReplaceBookApplyForm(forms.Form):
    SELECT = (
        ('preview', "预览"),
        ('save', "保存"),
    )
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)
    book_id = forms.CharField(label="书籍编号", max_length=10)
    p_or_s = forms.ChoiceField(choices=SELECT, widget=forms.RadioSelect)

    def get_rule(self):
        if self.is_valid():
            return ReplaceRule(
                self.cleaned_data['rule_res'],
                self.cleaned_data['replace_to'],
            )
        else:
            raise forms.ValidationError()

    def get_book(self):
        if self.is_valid():
            return Book.objects.get(pk=self.cleaned_data['book_id'])
        else:
            raise forms.ValidationError()


class ReplacePageApplyForm(forms.Form):
    SELECT = (
        ('preview', "预览"),
        ('save', "保存"),
    )
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)
    page_number = forms.CharField(label="章节编号", max_length=10)
    p_or_s = forms.ChoiceField(choices=SELECT, widget=forms.RadioSelect)

    def get_rule(self):
        if self.is_valid():
            return ReplaceRule(
                self.cleaned_data['rule_res'],
                self.cleaned_data['replace_to'],
            )
        else:
            raise forms.ValidationError()

    def get_page(self):
        if self.is_valid():
            return BookPage.objects.get(page_number=self.cleaned_data['page_number'])
        else:
            raise forms.ValidationError()

booksite/booksite/background/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseBadRequest
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.db.models import Max
from django.db.models import Count
from booksite.book.models import Book, BookPage, BookRank, KeyValueStorage
from booksite.book.tasks import get_new_book_with_book_name
from booksite.ajax import must_ajax, ajax_error, ajax_success, params_required
from .models import ReplaceRule, FengTui, JingTui, NewBookLog
from .forms import (
    ReplaceRuleCreateForm,
    ReplacePageApplyForm,
    ReplaceBookApplyForm,
    TuiJianForm,
)


@permission_required('usercenter.can_add_user')
def index(request):
    C = {}
    CATEGORYS_KV, created = KeyValueStorage.objects.get_or_create(
        key='CATEGORYS',
        defaults={'value': '', 'long_value': ''}
    )
    if created:
        real_categorys = Book.objects.order_by('category').distinct(
            'category').values_list('category', flat=True)
        CATEGORYS_KV.val = {chr(x[0]): x[1]
                            for x in zip(range(97, 123), real_categorys)}
        CATEGORYS_KV.save()
    CATEGORYS = [x[1] for x in CATEGORYS_KV.val.items() if x[1]]
    book_count = Book.objects.all().count()
    bookpage_count = BookPage.objects.all().count()
    bookrank_count = BookRank.objects.all().count()
    category_data = [
        [c, Book.objects.filter(category=c).count()] for c in CATEGORYS
    ]
    category_data = sorted(category_data, key=lambda x: x[1])
    C['category_data'] = json.dumps(category_data)
    C['book_count'] = book_count
    C['bookpage_count'] = bookpage_count
    C['bookrank_count'] = bookrank_count
    C['average_page_per_book'] = bookpage_count // book_count
    return render(request, "background/index.html", C)


@permission_required('usercenter.can_add_user')
def replace(request):
    C = {}
    form = ReplaceRuleCreateForm()
    if request.method == "POST":
        form = ReplaceRuleCreateForm(request.POST)
        if form.is_valid():
            form.save()
    replace_rule = ReplaceRule.all()
    C['replace_rule'] = replace_rule
    C['create_rule_form'] = form
    return render(request, "background/replace.html", C)


@permission_required('usercenter.can_add_user')
def edit_rule(request, pk=None):
    C = {}
    rule = ReplaceRule.get(pk)
    form = ReplaceRuleCreateForm({
        'rule_res': rule.rule_res,
        'replace_to': rule.replace_to,
    })
    if request.method == "POST":
        form = ReplaceRuleCreateForm(request.POST)
        if form.is_valid():
            rule.rule_res = form.cleaned_data['rule_res']
            rule.replace_to = form.cleaned_data['replace_to']
            rule.save()
            return redirect('bbg:replace')
    replace_rule = ReplaceRule.all()
    C['replace_rule'] = replace_rule
    C['create_rule_form'] = form
    C['edit_rule'] = True
    return render(request, "background/replace_edit.html", C)


@permission_required('usercenter.can_add_user')
def delete_rule(request, pk=None):
    rule = ReplaceRule.get(pk)
    rule.delete()
    return redirect(request.META['HTTP_REFERER'])


@permission_required('usercenter.can_add_user')
def apply_rule(request, pk=None):
    C = {}
    rule = ReplaceRule.get(pk)
    C['rule'] = rule
    book_id = request.GET.get('bi', '')
    page_number = request.GET.get('pn', '')
    C['book_id'] = book_id
    C['page_number'] = page_number
    this_is_save = request.method == "POST" and request.POST.get('save', None)
    if not book_id and page_number:
        page = BookPage.objects.get(page_number=page_number)
        page_content = page.get_content()
        if this_is_save:
            page_content = rule.replace(page_content)
            page.set_content(page_content)
        page.content_file.close()
        C['save'] = this_is_save
        C['r_content'] = rule.replace(page_content).replace('\n', '\n\n')
        C['content'] = page_content.replace('\n', '\n\n')
        C['page_admin_url'] = page.get_absolute_url()
        return render(request, "background/replace_apply.html", C)
    elif book_id:
        book = get_object_or_404(Book, pk=book_id)
        book_pages = BookPage.objects.filter(book_number=book.book_number)
        r_content_list = []
        apply_rule_url = reverse("bbg:apply_rule", args=[pk])
        for page in book_pages:
            page_content = page.get_content()
            if rule.match(page_content):
                page_preview_link = apply_rule_url + \
                    "?pn=%s" % page.page_number
                link_a = "<a href='%s' target='_blank'>%s</a>" % (
                    page_preview_link, page.title)
                if this_is_save:
                    page_content = rule.replace(page_content)
                    page.set_content(page_content)
                    r_content_list.append(link_a)
                else:
                    r_content_list.append(link_a)
                    for i in rule.findall(page_content):
                        r_content_list.append(i)
            page.content_file.close()
        C['save'] = this_is_save
        C['r_content'] = "\n".join(r_content_list)
        return render(request, "background/replace_apply.html", C)
    raise Http404


@permission_required('usercenter.can_add_user')
def replace_page(request):
    C = {}
    form = ReplacePageApplyForm(initial=request.GET)
    if request.method == "POST":
        form = ReplacePageApplyForm(request.POST)
        if form.is_valid():
            rule = form.get_rule()
            page = form.get_page()
            page_content = page.get_content()
            if form.cleaned_data['p_or_s'] == 'save':
                page_content = rule.replace(page_content)
                page.set_content(page_content)
                C['save'] = True
            page.content_file.close()
            C['r_content'] = rule.replace(page_content).replace('\n', '\n\n')
            C['content'] = page_content.replace('\n', '\n\n')
            C['page_admin_url'] = "/admin/book/bookpage/%d/" % (page.pk)
    C['create_rule_form'] = form
    return render(request, "background/replace_page.html", C)


@permission_required('usercenter.can_add_user')
def replace_book(request):
    C = {}
    form = ReplaceBookApplyForm(initial=request.GET)
    if request.method == "POST":
        form = ReplaceBookApplyForm(request.POST)
        if form.is_valid():
            rule = form.get_rule()
            book = form.get_book()
            book_pages = BookPage.objects.filter(book_number=book.book_number)
            r_content_list = []
            this_is_save = form.cleaned_data['p_or_s'] == 'save'
            for page in book_pages:
                content = page.get_content()
                if rule.match(content):
                    link_a = "<a href='%s' target='_blank'>%s</a>" % (
                        page.get_absolute_url(), page.title)
                    if this_is_save:
                        content = rule.replace(content)
                        page.set_content(content)
                        r_content_list.append(link_a)
                    else:
                        r_content_list.append(link_a)
                        for i in rule.findall(content):
                            r_content_list.append(i)
                page.content_file.close()
            C['save'] = this_is_save
            C['r_content'] = "\n".join(r_content_list)
    C['create_rule_form'] = form
    return render(request, "background/replace_book.html", C)


@permission_required('usercenter.can_add_user')
def tuijian(request):
    C = {}
    C['ft_books'] = FengTui().books or []
    C['jt_books'] = JingTui().books or []
    C['create_ft_form'] = TuiJianForm(model=FengTui)
    C['create_jt_form'] = TuiJianForm(model=JingTui)
    return render(request, 'background/tuijian.html', C)


@permission_required('usercenter.can_add_user')
def fengtui_create(request):
    C = {}
    if request.method == "POST":
        form = TuiJianForm(model=FengTui, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bbg:tuijian")
        else:
            C['ft_books'] = FengTui().books
            C['jt_books'] = JingTui().books
            C['create_jt_form'] = TuiJianForm(model=JingTui)
            C['create_ft_form'] = form
            return render(request, 'background/tuijian.html', C)
    else:
        return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def jingtui_create(request):
    C = {}
    if request.method == "POST":
        form = TuiJianForm(model=JingTui, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bbg:tuijian")
        else:
            C['ft_books'] = FengTui().books
            C['jt_books'] = JingTui().books
            C['create_jt_form'] = form
            C['create_ft_form'] = TuiJianForm(model=FengTui)
            return render(request, 'background/tuijian.html', C)
    else:
        return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def del_tuijian(request, model='ft', book_id=0):
    if model not in ['ft', 'jt'] and not Book.objects.filter(id=book_id):
        return redirect("bbg:tuijian")
    book = Book.objects.get(id=book_id)
    if model == 'ft':
        ft = FengTui()
        ft.remove(book)
        ft.save()
    if model == 'jt':
        jt = JingTui()
        jt.remove(book)
        jt.save()
    return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def book_search(request):
    C = {}
    C['cq'] = 'all'
    query_text = request.GET.get('q')
    category_query = request.GET.get('cq')
    ordered_field = request.GET.get('od', 'default')
    order_select = [
        {'val': 'default', 'name': "默认排序"},

booksite/booksite/background/templates/background/booksearch.html
{% extends "background/base.html" %}
{% block pagetitle %}: 书籍搜索{% endblock %}
{% block content %}
  <div id="NAVID" data-nav="booksearch"></div>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading">书籍搜索</div>
        <div class="panel-body">
          <form action="." method="GET" class="form-inline">
            <div class="form-group">
              <label for="search" class="sr-only control-label">关键词</label>
              <input
                id="search"
                placeholder="关键词"
                type="text"
                value="{{query_text|default_if_none:''}}"
                name="q"
                class="form-control"/>
            </div>
            <div class="form-group">
              <label for="category" class="sr-only control-label">分类</label>
              <select id="category" type="text" name="cq" class="form-control">
                {% if cq == 'all' %}
                  <option value="all" selected="selected">所有分类</option>
                {% else %}
                  <option value="all">所有分类</option>
                {% endif %}
                {% for c in categorys %}
                  {% if cq == c.name %}
                    <option value="{{c.name}}" selected="selected">{{c.name}}</option>
                  {% else %}
                    <option value="{{c.name}}">{{c.name}}</option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
            <div class="form-group">
              <label for="order" class="sr-only control-label">排序</label>
              <select id="order" type="text" name="od" class="form-control">
                {% for k in orderkey %}
                  {% if ordered == k.val %}
                    <option value="{{k.val}}" selected="selected">{{k.name}}</option>
                  {% else %}
                    <option value="{{k.val}}">{{k.name}}</option>
                  {% endif %}
                {% endfor %}
              </select>
            </div>
            <button type="submit" class="btn btn-success btn-sm">提交</button>
            <div style="margin:0;" class="btn-group pull-right btn-flat">
              <a href="javascript:;" class="btn btn-primary btn-sm withripple">批量操作
                <div class="ripple-wrapper"></div>
              </a>
              <a
                href="javascript:;"
                data-toggle="dropdown"
                class="btn btn-primary btn-sm dropdown-toggle withripple">
                <span class="caret"></span>
                <div class="ripple-wrapper"></div>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'bbg:book_jiuzhenggengxin' %}">自动纠新</a>
                </li>
                <li>
                  <a href="{% url 'bbg:book_page_next_zipper' %}">修复中断章节</a>
                </li>
              </ul>
            </div>
          </form>
          {% if books %}
            <table class="table">
              <thead>
                <tr>
                  <th>书名</th>
                  <th>作者</th>
                  <th style="width:73px;">分类</th>
                  <th style="width:450px;">章节</th>
                  <th style="width:75px;">更新时间</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                {% for book in books %}
                  <tr>
                    <td title="{{book.book_number}}">{{book.title|force_escape}}<br/>
                      <a{%
                        tabindex="0"
                        role="button"
                        data-toggle="popover"
                        data-trigger="focus"
                        data-content="{{book.info}}"
                        class="btn btn-xs btn-success" title="{{book.title}}" >简介</a>
                    </td>
                    <td>{{book.author|force_escape}}</td>
                    <td>{{book.category|force_escape}}</td>
                    <td>
                      <span>最新：</span>
                      <a href="{{book.last_page.get_absolute_url}}" target="_blank" class="new">{{book.last_page.title_html|force_escape}}</a><br/>
                      <span>最后：</span>
                      <a href="{{book.get_last_page.get_absolute_url}}" target="_blank" class="last">{{book.get_last_page.title_html|force_escape}}</a>
                    </td>
                    <td>{{book.last_update|date:"y-m-d"|force_escape}}</td>
                    <td>
                      <a
                        href="javascript:;"
                        data-bookid="{{book.id}}"
                        title="纠正最新章节"
                        data-toggle="tooltip"
                        data-placement="top"
                        class="btn btn-xs btn-info bookjx">纠新</a><br/>
                      <a
                        href="javascript:;"
                        data-bookid="{{book.id}}"
                        title="封面推荐本书"
                        data-toggle="tooltip"
                        data-placement="left"
                        class="btn btn-xs btn-info bookft">封推</a><br/>
                      <a
                        href="javascript:;"
                        data-bookid="{{book.id}}"
                        title="精品推荐本书"
                        data-toggle="tooltip"
                        data-placement="left"
                        class="btn btn-xs btn-info bookjt">精推</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
          {% if pagination.has_other_pages %}
            <div class="col-md-12 col-xs-12 col-sm-12 text-center">
              <ul class="pagination">
                {% if pagination.has_previous %}
                  <li>
                    <a href="#" data-num="1">&lt;&lt;</a>
                  </li>
                  <li>
                    <a href="#" data-num="{{pagination.previous_page_number}}">&lt;</a>
                  </li>
                {% endif %}
                <li class="active">
                  <span>{{pagination.number|force_escape}}</span>
                </li>
                {% if pagination.has_next %}
                  <li>
                    <a href="#" data-num="{{pagination.next_page_number}}">&gt;</a>
                  </li>
                  <li>
                    <a
                      href="#"
                      data-num="{{pagination.paginator.num_pages}}"
                      class="fui-arrow-right">&gt;&gt;</a>
                  </li>
                {% endif %}
                <li class="disabled">
                  <a href="javascript:;">共（{{pagination.paginator.num_pages}}）页，{{pagination.paginator.count}}条数据</a>
                </li>
              </ul>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footerjs %}
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
      $('[data-toggle="popover"]').popover();
      $('.bookjx').click(function () {
        var bookid = $(this).data('bookid');
        var last_page = $(this)
          .parents('tr')
          .find("span.last")
          .eq(0);
        var new_page = $(this)
          .parents('tr')
          .find("span.new")
          .eq(0);
        $.ajax({
          data    : {
            book_id: bookid
          },
          dataType: 'json',
          error   : function (xhr, status, error) {
            alert("请求失败！Status: " + status + " Content: " + xhr.responseText);
          },
          method  : "POST",
          success : function (data) {
            new_page.text(last_page.text());
            alert("纠正新章节成功！");
          },
          url     : "{% url 'bbg:book_jx' %}"
        });
        return false;
      });
      $('.bookft').click(function () {
        var bookid = $(this).data('bookid');
        $.ajax({
          data    : {
            book_id: bookid
          },
          dataType: 'json',
          error   : function (xhr, status, error) {
            alert("请求失败！Status: " + status + " Content: " + xhr.responseText);
          },
          method  : "POST",
          success : function (data) {
            alert("封推成功！");
          },
          url     : "{% url 'bbg:book_ft' %}"
        });
        return false;
      });
      $('.bookjt').click(function () {
        var bookid = $(this).data('bookid');
        $.ajax({
          data    : {
            book_id: bookid
          },
          dataType: 'json',
          error   : function (xhr, status, error) {
            alert("请求失败！Status: " + status + " Content: " + xhr.responseText);
          },
          method  : "POST",
          success : function (data) {
            alert("精推成功！");
          },
          url     : "{% url 'bbg:book_jt' %}"
        });
        return false;
      });
    })
  </script>
{% endblock %}

booksite/booksite/background/templates/background/replace_edit.html
{% extends "background/base.html" %}
{% block pagetitle %}: 内容替换{% endblock %}
{% block content %}
  <div id="NAVID" data-nav="replace"></div>
  <div class="row">
    <div class="col-xs-6">
      <div class="panel panel-primary">
        <div class="panel-heading">替换规则
          <button
            data-target="#myModal"
            data-toggle="modal"
            class="btn btn-sm btn-success pull-right">创建</button>
        </div>
        <div class="panel-body">
          <table class="table">
            <thead>
              <tr>
                <td>规则</td>
                <td style="width:150px;">操作</td>
              </tr>
            </thead>
            <tbody>
              {% for rep in replace_rule %}
                <tr>
                  <td>{{rep|force_escape}}</td>
                  <td class="table-action">
                    <button data-pk='{{rep.pk}}' class="btn btn-xs btn-primary apply-rule">应用</button>
                    <a href="{%url 'bbg:edit_rule' rep.db_data.pk%}" class="btn btn-xs btn-success">编辑</a>
                    <a
                      href="{%url 'bbg:delete_rule' rep.db_data.pk%}"
                      class="btn btn-xs btn-danger">删除</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="panel panel-primary">
        <div class="panel-heading">替换历史</div>
        <div class="panel-body"></div>
      </div>
    </div>
  </div>
  <div
    id="myModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="myModalLabel"
    aria-hidden="true"
    class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <form id="newRuleForm" action="." method="POST" class="form-horizontal">
          <div class="modal-header">
            <button data-dismiss="modal" class="close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 id="myModalLabel" class="modal-title">创建替换规则</h4>
          </div>
          <div class="modal-body">{% csrf_token %}
            {% with create_rule_form as CRF %}
            <div class="form-group {%if CRF.rule_res.errors%}has-error{%endif%}">
              <label for="inputRe" class="col-lg-2 control-label">{{CRF.rule_res.label}}</label>
              <div class="col-lg-10">
                <input
                  id="inputRe"
                  name="rule_res"
                  type="text"
                  value="{{CRF.rule_res.value|default:''}}"
                  class="form-control"/>
                <span class="help-block">{{CRF.rule_res.errors}}</span>
              </div>
            </div>
            <div class="form-group {%if CRF.replace_to.errors%}has-error{%endif%}">
              <label for="inputReplace" class="col-lg-2 control-label">{{CRF.replace_to.label}}</label>
              <div class="col-lg-10">
                <input
                  id="inputReplace"
                  type="text"
                  value="{{CRF.replace_to.value|default:''}}"
                  name="replace_to"
                  class="form-control"/>
                <span class="help-block">{{CRF.replace_to.errors}}</span>
              </div>
            </div>{% endwith %}
            <div class="modal-footer">
              <button data-dismiss="modal" class="btn btn-default btn-raised">关闭</button>
              <button type="submit" class="btn btn-primary btn-raised">保存</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block footerjs %}
  <script>
    $(function () {
      {% if create_rule_form.errors or edit_rule %}
        $("#myModal").modal('show')
      {% endif %}
    });
  </script>
{% endblock %}