booksite/booksite/background/urls.py
# -*- encoding:utf-8 -*-
from django.conf.urls import url
from .views import (
    index,
    replace,
    delete_rule, edit_rule, apply_rule,
    replace_page, replace_book,
    tuijian, fengtui_create, jingtui_create,
    del_tuijian,
    book_search, book_jx, book_ft, book_jt,
    book_jiuzhenggengxin,
    book_page_next_zipper,
    get_new_book,
)

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^replace/$', replace, name="replace"),
    url(r'^replace/delete/(?P<pk>\d+)/$', delete_rule, name="delete_rule"),
    url(r'^replace/edit/(?P<pk>\d+)/$', edit_rule, name="edit_rule"),
    url(r'^replace/apply/(?P<pk>\d+)/$', apply_rule, name="apply_rule"),
    url(r'^replace/page/$', replace_page, name="replace_page"),
    url(r'^replace/book/$', replace_book, name="replace_book"),
    url(r'^tuijian/$', tuijian, name="tuijian"),
    url(r'^tuijian/create/fengtui/$', fengtui_create, name="fengtui_create"),
    url(r'^tuijian/create/jingtui/$', jingtui_create, name="jingtui_create"),
    url(r'^tuijian/delete/(?P<model>ft|jt)/(?P<book_id>\d+)/$', del_tuijian, name="del_tuijian"),
    url(r'^booksearch/$', book_search, name="book_search"),
    url(r'^booksearch/jx/$', book_jx, name="book_jx"),
    url(r'^booksearch/ft/$', book_ft, name="book_ft"),
    url(r'^booksearch/jt/$', book_jt, name="book_jt"),
    url(r'^booksearch/jxall/$', book_jiuzhenggengxin, name="book_jiuzhenggengxin"),
    url(r'^booksearch/pagezipper/$', book_page_next_zipper, name="book_page_next_zipper"),
    url(r'^newbook/$', get_new_book, name="newbook"),
]

booksite/booksite/book/urls.py
# -*- encoding:utf-8 -*-

from django.conf.urls import url

from .views import (
    home, category, bookrank, booknews,
    bookindex, bookpage, bookinfo, bookindexajax,
    load_nall_page, page_fix_pic, book_fix_pic,
    page_task_check, edit_line, del_line
)

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^fenlei/(?P<category>[a-z])/$', category, name='category'),
    url(r'^bookrank/$', bookrank, name='bookrank'),
    url(r'^booknews/$', booknews, name='booknews'),
    url(r'^book/(?P<book_id>\d+)/$', bookindex, name='bookindex'),
    url(r'^bookinfo/(?P<book_id>\d+)/$', bookinfo, name='bookinfo'),
    url(r'^bookindex/(?P<book_id>\d+)/$', bookindexajax, name='bookindexajax'),
    url(r'^book/(?P<book_id>\d+)/(?P<page_number>\d+)/$', bookpage, name='bookpage'),

    url(r'^nallpage/(?P<page_id>\d+)/$', load_nall_page, name='nallpage'),
    url(r'^fixpic/page/(?P<page_id>\d+)/$', page_fix_pic, name='pagefixpic'),
    url(r'^fixpic/book/(?P<book_id>\d+)/$', book_fix_pic, name='bookfixpic'),
    url(r'^taskcheck/page/(?P<page_id>\d+)/$', page_task_check, name='pagetaskcheck'),
    url(r'^lineupdate/$', edit_line, name="lineupdate"),
    url(r'^lineremove/(?P<page_id>\d+)/$', del_line, name="del_line"),
]

booksite/booksite/h5/urls.py
# -*- encoding:utf-8 -*-
from django.conf.urls import url
from .views import (
    bookindex, bookpage,
    index, load,
    search, searchload
)

urlpatterns = [
    url(r'^$', index, name='h5'),
    url(r'^load/$', load, name='load'),
    url(r'^search/$', search, name='search'),
    url(r'^searchload/$', searchload, name='searchload'),
    url(r'^book/(?P<book_id>\d+)/$', bookindex, name='bookindex'),
    url(r'^page/(?P<page_number>\d+)/$', bookpage, name='bookpage'),
]

booksite/booksite/urls.py
# -*- coding: utf-8 -*-
import django.contrib.auth.views
from django.contrib.sitemaps import views as sitemap_views
# from django.views.generic.base import TemplateView
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from graphene_django.views import GraphQLView
from booksite.usercenter.views import (
    login_view, signup, logout_view
)
from booksite.sitemap import BookSitemaps
admin.autodiscover()

sitemaps = {
    'books': BookSitemaps()
}

html5_urls = [
    url(r'', include('booksite.h5.urls')),
    url(r'account/', include('booksite.usercenter.mburls')),
]

password_reset_urls = [
    url(r'^$', django.contrib.auth.views.password_reset,
       {'template_name': 'usercenter/password_reset_form.html',
        'email_template_name': 'usercenter/password_reset_email.html',}, name='password_reset'),
    url(r'^done/$', django.contrib.auth.views.password_reset_done,
        {'template_name': 'usercenter/password_reset_done.html'}, name='password_reset_done'),
    url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', django.contrib.auth.views.password_reset_confirm,
        {'template_name': 'usercenter/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^complete/$', django.contrib.auth.views.password_reset_complete,
        {'template_name': 'usercenter/password_reset_complete.html'}, name='password_reset_complete'),
]

urlpatterns = [
    url(r'', include('booksite.book.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^comments/', include('django_comments.urls')),

    url(r'^sitemap.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps}),
    url(r'^robots.txt', include('robots.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^usercenter/', include('booksite.usercenter.urls')),
    url(r'^login/$', login_view, name='login'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^resetpassword/', include(password_reset_urls)),

    url(r'^mobile/', include((html5_urls,'h5',), namespace=None)),

    url(r'^bbg/', include('booksite.background.urls', namespace='bbg', app_name='booksite.background')),
]


if settings.DEBUG:
    import booksite.book.views
    urlpatterns += [url(r'^media/book/(?P<path>.*)$', booksite.book.views.bookpage_zip, name='zippage')]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksite/booksite/background/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseBadRequest
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.db.models import Max
from django.db.models import Count
from booksite.book.models import Book, BookPage, BookRank, KeyValueStorage
from booksite.book.tasks import get_new_book_with_book_name
from booksite.ajax import must_ajax, ajax_error, ajax_success, params_required
from .models import ReplaceRule, FengTui, JingTui, NewBookLog
from .forms import (
    ReplaceRuleCreateForm,
    ReplacePageApplyForm,
    ReplaceBookApplyForm,
    TuiJianForm,
)


@permission_required('usercenter.can_add_user')
def index(request):
    C = {}
    CATEGORYS_KV, created = KeyValueStorage.objects.get_or_create(
        key='CATEGORYS',
        defaults={'value': '', 'long_value': ''}
    )
    if created:
        real_categorys = Book.objects.order_by('category').distinct(
            'category').values_list('category', flat=True)
        CATEGORYS_KV.val = {chr(x[0]): x[1]
                            for x in zip(range(97, 123), real_categorys)}
        CATEGORYS_KV.save()
    CATEGORYS = [x[1] for x in CATEGORYS_KV.val.items() if x[1]]
    book_count = Book.objects.all().count()
    bookpage_count = BookPage.objects.all().count()
    bookrank_count = BookRank.objects.all().count()
    category_data = [
        [c, Book.objects.filter(category=c).count()] for c in CATEGORYS
    ]
    category_data = sorted(category_data, key=lambda x: x[1])
    C['category_data'] = json.dumps(category_data)
    C['book_count'] = book_count
    C['bookpage_count'] = bookpage_count
    C['bookrank_count'] = bookrank_count
    C['average_page_per_book'] = bookpage_count // book_count
    return render(request, "background/index.html", C)


@permission_required('usercenter.can_add_user')
def replace(request):
    C = {}
    form = ReplaceRuleCreateForm()
    if request.method == "POST":
        form = ReplaceRuleCreateForm(request.POST)
        if form.is_valid():
            form.save()
    replace_rule = ReplaceRule.all()
    C['replace_rule'] = replace_rule
    C['create_rule_form'] = form
    return render(request, "background/replace.html", C)


@permission_required('usercenter.can_add_user')
def edit_rule(request, pk=None):
    C = {}
    rule = ReplaceRule.get(pk)
    form = ReplaceRuleCreateForm({
        'rule_res': rule.rule_res,
        'replace_to': rule.replace_to,
    })
    if request.method == "POST":
        form = ReplaceRuleCreateForm(request.POST)
        if form.is_valid():
            rule.rule_res = form.cleaned_data['rule_res']
            rule.replace_to = form.cleaned_data['replace_to']
            rule.save()
            return redirect('bbg:replace')
    replace_rule = ReplaceRule.all()
    C['replace_rule'] = replace_rule
    C['create_rule_form'] = form
    C['edit_rule'] = True
    return render(request, "background/replace_edit.html", C)


@permission_required('usercenter.can_add_user')
def delete_rule(request, pk=None):
    rule = ReplaceRule.get(pk)
    rule.delete()
    return redirect(request.META['HTTP_REFERER'])


@permission_required('usercenter.can_add_user')
def apply_rule(request, pk=None):
    C = {}
    rule = ReplaceRule.get(pk)
    C['rule'] = rule
    book_id = request.GET.get('bi', '')
    page_number = request.GET.get('pn', '')
    C['book_id'] = book_id
    C['page_number'] = page_number
    this_is_save = request.method == "POST" and request.POST.get('save', None)
    if not book_id and page_number:
        page = BookPage.objects.get(page_number=page_number)
        page_content = page.get_content()
        if this_is_save:
            page_content = rule.replace(page_content)
            page.set_content(page_content)
        page.content_file.close()
        C['save'] = this_is_save
        C['r_content'] = rule.replace(page_content).replace('\n', '\n\n')
        C['content'] = page_content.replace('\n', '\n\n')
        C['page_admin_url'] = page.get_absolute_url()
        return render(request, "background/replace_apply.html", C)
    elif book_id:
        book = get_object_or_404(Book, pk=book_id)
        book_pages = BookPage.objects.filter(book_number=book.book_number)
        r_content_list = []
        apply_rule_url = reverse("bbg:apply_rule", args=[pk])
        for page in book_pages:
            page_content = page.get_content()
            if rule.match(page_content):
                page_preview_link = apply_rule_url + \
                    "?pn=%s" % page.page_number
                link_a = "<a href='%s' target='_blank'>%s</a>" % (
                    page_preview_link, page.title)
                if this_is_save:
                    page_content = rule.replace(page_content)
                    page.set_content(page_content)
                    r_content_list.append(link_a)
                else:
                    r_content_list.append(link_a)
                    for i in rule.findall(page_content):
                        r_content_list.append(i)
            page.content_file.close()
        C['save'] = this_is_save
        C['r_content'] = "\n".join(r_content_list)
        return render(request, "background/replace_apply.html", C)
    raise Http404


@permission_required('usercenter.can_add_user')
def replace_page(request):
    C = {}
    form = ReplacePageApplyForm(initial=request.GET)
    if request.method == "POST":
        form = ReplacePageApplyForm(request.POST)
        if form.is_valid():
            rule = form.get_rule()
            page = form.get_page()
            page_content = page.get_content()
            if form.cleaned_data['p_or_s'] == 'save':
                page_content = rule.replace(page_content)
                page.set_content(page_content)
                C['save'] = True
            page.content_file.close()
            C['r_content'] = rule.replace(page_content).replace('\n', '\n\n')
            C['content'] = page_content.replace('\n', '\n\n')
            C['page_admin_url'] = "/admin/book/bookpage/%d/" % (page.pk)
    C['create_rule_form'] = form
    return render(request, "background/replace_page.html", C)


@permission_required('usercenter.can_add_user')
def replace_book(request):
    C = {}
    form = ReplaceBookApplyForm(initial=request.GET)
    if request.method == "POST":
        form = ReplaceBookApplyForm(request.POST)
        if form.is_valid():
            rule = form.get_rule()
            book = form.get_book()
            book_pages = BookPage.objects.filter(book_number=book.book_number)
            r_content_list = []
            this_is_save = form.cleaned_data['p_or_s'] == 'save'
            for page in book_pages:
                content = page.get_content()
                if rule.match(content):
                    link_a = "<a href='%s' target='_blank'>%s</a>" % (
                        page.get_absolute_url(), page.title)
                    if this_is_save:
                        content = rule.replace(content)
                        page.set_content(content)
                        r_content_list.append(link_a)
                    else:
                        r_content_list.append(link_a)
                        for i in rule.findall(content):
                            r_content_list.append(i)
                page.content_file.close()
            C['save'] = this_is_save
            C['r_content'] = "\n".join(r_content_list)
    C['create_rule_form'] = form
    return render(request, "background/replace_book.html", C)


@permission_required('usercenter.can_add_user')
def tuijian(request):
    C = {}
    C['ft_books'] = FengTui().books or []
    C['jt_books'] = JingTui().books or []
    C['create_ft_form'] = TuiJianForm(model=FengTui)
    C['create_jt_form'] = TuiJianForm(model=JingTui)
    return render(request, 'background/tuijian.html', C)


@permission_required('usercenter.can_add_user')
def fengtui_create(request):
    C = {}
    if request.method == "POST":
        form = TuiJianForm(model=FengTui, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bbg:tuijian")
        else:
            C['ft_books'] = FengTui().books
            C['jt_books'] = JingTui().books
            C['create_jt_form'] = TuiJianForm(model=JingTui)
            C['create_ft_form'] = form
            return render(request, 'background/tuijian.html', C)
    else:
        return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def jingtui_create(request):
    C = {}
    if request.method == "POST":
        form = TuiJianForm(model=JingTui, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bbg:tuijian")
        else:
            C['ft_books'] = FengTui().books
            C['jt_books'] = JingTui().books
            C['create_jt_form'] = form
            C['create_ft_form'] = TuiJianForm(model=FengTui)
            return render(request, 'background/tuijian.html', C)
    else:
        return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def del_tuijian(request, model='ft', book_id=0):
    if model not in ['ft', 'jt'] and not Book.objects.filter(id=book_id):
        return redirect("bbg:tuijian")
    book = Book.objects.get(id=book_id)
    if model == 'ft':
        ft = FengTui()
        ft.remove(book)
        ft.save()
    if model == 'jt':
        jt = JingTui()
        jt.remove(book)
        jt.save()
    return redirect("bbg:tuijian")


@permission_required('usercenter.can_add_user')
def book_search(request):
    C = {}
    C['cq'] = 'all'
    query_text = request.GET.get('q')
    category_query = request.GET.get('cq')
    ordered_field = request.GET.get('od', 'default')
    order_select = [
        {'val': 'default', 'name': "默认排序"},

booksite/booksite/templates/baidutongji.html
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?{{BAIDUTONGJI_ID}}";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

booksite/booksite/templates/base.html
{% load static %}
{% load assets %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<title>{% spaceless %}{% block pagetitle %}这里是{% endblock pagetitle %}{% endspaceless %} -- 看小说么</title>
	<meta name="keywords" content="{% spaceless %}{% block keymeta %}看小说么,玄幻小说,侦探小说,网游小说,武侠小说,都市小说,历史小说,言情小说,网络小说,网络文学{% endblock keymeta %}{% endspaceless %}">
	<meta name="description" content="{% spaceless %}{% block keydesc %}看小说,么?最简洁的小说阅读网站,提供都市小说.玄幻小说.仙侠小说.历史小说.网游小说.免费小说等在线阅读.{% endblock keydesc %}{% endspaceless %}">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<link rel="apple-touch-icon" href="{% static 'img/iapp.ico.jpg' %}">
	<link rel="shortcut icon" href="{% static 'img/iapp.ico.jpg' %}" type="image/x-icon">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-title" content="看小说么">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	{% assets "css_all" %}
		<link href="{{ ASSET_URL }}" rel="stylesheet">
	{% endassets %}
	{% if BAIDUTONGJI_ID %}
		{% include "baidutongji.html" %}
	{% endif %}
	{% if GA_ID %}
		{% include "googleanalytics.html" %}
	{% endif %}
	{% block headercss %}
	{% endblock headercss %}
	{% block headerjs %}
	<script>var DATA_DIC = DATA_DIC || {}</script>
	{% endblock headerjs %}

</head>
<body class="inv{% if invert %} invert{% endif %}">
{% spaceless %}
	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">看小说么?</a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav main">
					<li class="dropdown" id="nav-category">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">{%if category%}{{category}}{% else %}书库索引{%endif%}</a>
						<span class="hidden-xs dropdown-arrow dropdown-arrow-inverse"></span>
						<ul class="dropdown-menu dropdown-inverse" role="menu">
							{% for ca in categorys %}
								{% if ca.name %}<li id="nav{{ca.key}}"><a href="{% url 'category' ca.key %}">{{ca.name}}</a></li>{% endif %}
							{% endfor %}
						</ul>
					</li>
					<li id="navp">
						<a href="{% url 'bookrank' %}?s=all_push">排行榜单</a>
					</li>
					<li id="navnews" class="hidden-sm">
						<a href="{% url 'booknews' %}">最近更新</a>
					</li>
					{% if user.is_superuser %}
					<li>
						<a href="{% url 'bbg:home' %}">管理后台</a>
					</li>
					{% endif %}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">个人中心{% if bookmark_update %} <span class="readpoint">&nbsp;</span>{% endif %}<span class="caret"></span></a>
						<span class="hidden-xs dropdown-arrow dropdown-arrow-inverse"></span>
						<ul class="dropdown-menu dropdown-inverse" role="menu">
							<li><a href="javascript:;">{{user.username}}</a></li>
							<li><a href="{% url 'changepwd' %}">修改密码</a></li>
							<li id="navbma"><a href="{% url 'bookmark' %}">我的书架{% if bookmark_update %} <span class="badge badge-danger">{{ bookmark_update }}</span>{% endif %}</a></li>
							<li class="divider"></li>
							<li><a href="{% url 'logout' %}">登出</a></li>
						</ul>
					</li>
					{% else %}
					<li><a href="{% url 'login' %}">登录</a></li>
					<li><a href="{% url 'signup' %}">注册</a></li>
					{% endif %}
				</ul>
				<form class="navbar-form navbar-right" action="/" method="get" role="search">
					<div class="form-control">
						<input name="s" class="form-control col-lg-8" id="navbarInput-01" type="search" placeholder="搜索书籍">
						<button class="btn btn-link" type="submit"><span class="input-icon glyphicon glyphicon-search"></span></button>
					</div>
				</form>
			</div>
		</div>
	</nav>
{% endspaceless %}
	<div class="container">
	{% block content %}{% endblock content %}
	</div>
	{% block footerblock %}{% endblock footerblock %}
	<footer class="bs-docs-footer inv">
		<div class="container text-center">
			<p>本网站由<a href="http://twitter.com/ouyanghongyu" target="_blank">@ouyanghongyu</a>设计与制作.</p>
			<p>更多信息请查看<a href="https://github.com/tkliuxing/bookspider">我的GitHub</a>.</p>
			<p>本项目源码受 <a href="https://github.com/tkliuxing/bookspider/blob/master/LICENSE" target="_blank">Apache</a> 开源协议保护. 本站收录文章版权归原作者所有.</p>
			<ul class="bs-docs-footer-links muted">
				<li>当前版本： v2.0</li>
				<li>·</li>
				<li><a href="https://github.com/tkliuxing/bookspider">GitHub 仓库</a></li>
				<li>·</li>
				<li><a href="https://github.com/tkliuxing/bookspider/issues?state=open">Issues</a></li>
			</ul>
		</div>
	</footer>
	{% assets "js_all" %}
		<script src="{{ ASSET_URL }}" rel="stylesheet"></script>
	{% endassets %}
	{% block footerjs %}
	{% endblock footerjs %}

</body>
</html>

booksite/booksite/templates/googleanalytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{GA_ID}}', 'auto');
  ga('send', 'pageview');

</script>